### ISSUE TITLE
UglifyJs throws error

### ISSUE THREAD

**Issue by giridharkl** [jonataswalker/ol-contextmenu#132]
UglifyJs is throwing error:

[echo] Building task management angular app
     [exec]
     [exec] @angular/compiler-cli@4.4.6 requires typescript@'>=2.1.0 <2.4.0' but 2.6.1 was found instead.
     [exec] Using this version can result in undefined behaviour and difficult to debug problems.
     [exec]
     [exec] Please run the following command to install a compatible version of TypeScript.
     [exec]
     [exec]     npm install typescript@'>=2.1.0 <2.4.0'
     [exec]
     [exec] To disable this warning run "ng set --global warnings.typescriptMismatch=false".
     [exec]
     [exec] [0m[0m
     [exec] [0mDate: [1m[37m2018-01-29T11:09:49.085Z[39m[22m[0m
     [exec] [0m[1m[31mERROR in vendor.b8ac280cccaff61c75c8.bundle.js from UglifyJs[39m[22m[0m
     [exec] [0mHash: [1m[37mbaf88294c6791d70b771[39m[22m[0m
     [exec] [0m[1m[31mUnexpected token: name (a) [vendor.b8ac280cccaff61c75c8.bundle.js:139516,468][39m[22m[0m
     [exec] [0mTime: [1m[

**Comment by jonataswalker** [comment]
No idea what this is about.

**Comment by omarriaga** [comment]
when you build an angular project with openlayers and ol-contextmenu generates that kind of error on compiling to production i have the same error because of minified and uglified js 

 node --max_old_space_size=3072 ./node_modules/.bin/ng build --prod  --aot --sm
Hash: 6aedeafaea025a27c7f4                                                                 
Time: 677671ms
chunk    {0} main.40ceabe55eaa9ca5dcb5.bundle.js, main.40ceabe55eaa9ca5dcb5.bundle.js.map (main) 11.1 MB {4} [initial] [rendered]
chunk    {1} polyfills.2e9542f68452054dab9f.bundle.js, polyfills.2e9542f68452054dab9f.bundle.js.map (polyfills) 193 kB {5} [initial] [rendered]
chunk    {2} scripts.751c442221624d8d25de.bundle.js, scripts.751c442221624d8d25de.bundle.js.map (scripts) 3.42 MB {5} [initial] [rendered]
chunk    {3} styles.58873c165f711be8f982.bundle.css, styles.58873c165f711be8f982.bundle.css.map (styles) 334 bytes {5} [initial] [rendered]
chunk    {4} vendor.5710d258e9453695fe47.bundle.js, vendor.5710d258e9453695fe47.bundle.js.map (vendor) 6.69 MB [initial] [rendered]
chunk    {5} inline.70d58e84ac5a9c8009d8.bundle.js, inline.70d58e84ac5a9c8009d8.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in vendor.5710d258e9453695fe47.bundle.js from UglifyJs
Unexpected token: name (a) [/Users/juan/angular_projects/sigcs-frontend/~/ol-contextmenu/dist/ol-contextmenu.js:7,505][vendor.5710d258e9453695fe47.bundle.js:116891,468]
